{
  "hash": "4e5925e4cf8bfd09283c81df395a6d8a",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"単回帰モデル\"\ndescription: \"模擬調査データで単回帰を実行・検証し、年齢を加えた重回帰と比較します。t 検定・分散分析との関係も扱います。\"\ndate: 2026-09-08\nformat: html\n# 日本語の図ラベルを描画するため、手元に導入済みのraggを使います。\nknitr:\n  opts_chunk:\n    dev: ragg_png\ndraft: true\n---\n\n## 目的\n\n1. 分析したい内容を言葉にし、AI に R のコードを依頼できます。\n2. 係数、p 値、決定係数、分析人数と図を確認し、結果を解釈できます。\n3. 年齢を加えた重回帰と単回帰の違いを説明できます。\n\n「年齢を加えた重回帰」までを読んで実行し、練習問題に取り組んでください。「t 検定・分散分析との関係」は、Moodle で指定された場合に取り組む節です。\n\n## 準備\n\n::: {.callout-note title=\"先に確認する動画\"}\nMoodle の解説動画「統計モデリングとは？」「線形モデル1（単回帰モデル）」を確認してください。\n:::\n\n### 回帰式の復習\n\n単回帰モデルとは、説明変数を1つ使って、被説明変数との関係を直線で表すモデルです。\n\n$$\ny_i = \\beta_0 + \\beta_1 x_i + \\varepsilon_i\n$$\n\n例えば、小学生の学年から身長を予測する場合を考えてみましょう。平均的な身長を $110 + 6 \\times \\text{学年}$ cm とするモデルでは、切片は110、傾きは6です。学年が1つ上の児童の平均身長が6cm高いという関係を表します。同じ学年でも身長には個人差があり、その違いを誤差項 $\\varepsilon_i$ で表します。\n\nここからは、成人の生活を想定した模擬調査データを使います。必要なときに頼れる人がいると感じる人ほど、生活満足度が高いのかを調べます。\n\n### CSV の読み込み\n\n[模擬調査データの CSV](../data/mock_survey.csv){download=\"mock_survey.csv\"}をダウンロードし、Positron で開いている作業フォルダに保存してください。これは架空の成人1,000人のデータです。実際の調査結果ではなく、質問項目も授業用に作ったものです。[質問文と変数の説明](../data/mock-survey.qmd)も参照できます。\n\n`readr` と `dplyr`、図を描く `ggplot2` を使います。tidyverse を導入済みなら、追加のインストールは不要です。未導入の場合だけ、次を一度実行してください。\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# CSVの読み込み、得点計算、作図に使います。\ninstall.packages(c(\"readr\", \"dplyr\", \"ggplot2\"))\n```\n:::\n\n\n次の準備コードは、上から順にそのまま実行してください。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey <- readr::read_csv(\"mock_survey.csv\", show_col_types = FALSE)\n```\n:::\n\n\n\n\n読み込み直後は1,000行・25列です。今回は欠損値を含まないデータを使います。\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndim(survey)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1000   25\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(is.na(survey))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n### 尺度得点の計算\n\nサポートと生活満足度は、それぞれ5項目で尋ねています。回答は1〜5で、各尺度の5番だけは他の項目と反対向きの質問です。例えば、`support_5` は「悩みがあっても、頼れる人がいない。」です。\n\n5番を `6 - 元の回答` で反転し、他の4項目と平均します。元の列は残し、反転した列の末尾に `_r` を付けます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_scored <- survey |>\n  dplyr::mutate(\n    support_5_r = 6 - support_5,\n    life_satisfaction_5_r = 6 - life_satisfaction_5\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_scored <- survey_scored |>\n  dplyr::mutate(\n    support_mean = (support_1 + support_2 + support_3 + support_4 + support_5_r) / 5,\n    life_satisfaction_mean = (life_satisfaction_1 + life_satisfaction_2 +\n      life_satisfaction_3 + life_satisfaction_4 + life_satisfaction_5_r) / 5\n  )\n```\n:::\n\n\n両方とも1〜5の得点で、高いほどサポートや生活満足度が高い向きになります。ここでは、項目の平均得点を連続変数とみなして分析します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_scored |>\n  dplyr::select(support_mean, life_satisfaction_mean) |>\n  summary()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  support_mean   life_satisfaction_mean\n Min.   :1.000   Min.   :1.000         \n 1st Qu.:2.200   1st Qu.:2.400         \n Median :3.000   Median :3.000         \n Mean   :2.967   Mean   :3.006         \n 3rd Qu.:3.600   3rd Qu.:3.800         \n Max.   :5.000   Max.   :5.000         \n```\n\n\n:::\n:::\n\n\n`|>` は、左側の処理結果を次の関数に渡す記号です。AI が使うことのある `%>%` も、ここで示す使い方では同じ働きをします。参照コードは `<-` と `|>` にそろえていますが、学生が使うコードの書き方は問いません。\n\n## 分析の仕様を言葉にする\n\n知りたいことは、サポートの得点が高い人ほど、生活満足度の得点も高いかどうかです。AI に依頼する前に、対象、変数の役割、モデル、欲しい出力を決めます。\n\n| 項目 | 今回の仕様 |\n|---|---|\n| データ | 準備で作った `survey_scored` |\n| 対象 | 全員1,000人。地域や就業区分で絞り込まない |\n| 被説明変数 | `life_satisfaction_mean`（生活満足度、数値、1〜5点） |\n| 説明変数 | `support_mean`（サポート、数値、1〜5点） |\n| モデル | 切片を含む単回帰。生活満足度をサポートに回帰する |\n| 数値の出力 | `summary()` の結果と、分析に使った人数 |\n| 図 | 横軸がサポート、縦軸が生活満足度の散布図と回帰直線。予測値と残差の散布図 |\n\nここでは年齢の違いは考慮していません。後で年齢を加え、結果を比べます。\n\n## AI への指示例\n\n「このデータで回帰分析をして」と頼むだけでは、どちらの変数を説明したいのか、誰を分析するのかが伝わりません。今回は次の完成例を使い、ブラウザの AI にコードを依頼してください。CSV や個々の回答は渡しません。\n\n::: {.callout-tip title=\"AI への指示例\"}\n```{.default .prompt}\nRで単回帰分析をしたいです。\nデータフレームsurvey_scoredは読み込みと得点計算が済んでいます。\n全員1,000人を使い、欠損値はありません。\nlife_satisfaction_meanは生活満足度、support_meanはサポートの平均得点で、\nどちらも1〜5の数値です。\nlife_satisfaction_meanを被説明変数、support_meanだけを説明変数とし、\n切片を含むモデルをlm()で推定してください。\nsummary()で結果を、nobs()で分析人数を表示してください。\nggplot2で、横軸をサポート、縦軸を生活満足度にした散布図を描き、\n同じ単回帰モデルの回帰直線を重ねてください。信頼帯は表示しません。\nさらに、横軸がこのモデルの予測値、縦軸が残差の散布図を描き、\n残差0の水平線を加えてください。点が重なるので半透明にしてください。\n図の軸ラベルは日本語にし、単位の「点」も付けてください。\n元データを変更せず、変数の標準化や対象者の絞り込みはしないでください。\n代入は <-、パイプは |> を使い、関数はできるだけパッケージ名を付けてください。\n推定、結果表示、作図を分け、短い説明を添えてください。\n```\n:::\n\n返ってきたコードを Positron のスクリプトに貼り、準備コードに続けて実行します。エラーが出たら、個人の回答データを含めず、エラーメッセージと該当するコードを AI に伝えて修正を依頼してください。\n\n## 参照コードと出力\n\n自分のコードを実行してから開き、結果を照合してください。オブジェクト名や関数の並べ方が違っていても、指定した対象とモデルが同じかを確かめます。\n\n::: {.callout-caution collapse=\"true\" title=\"単回帰の参照コードと出力（実行してから開く）\"}\n\n`~` の左側が被説明変数、右側が説明変数です。通常の `lm()` では切片も推定します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_simple <- lm(life_satisfaction_mean ~ support_mean, data = survey_scored)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_simple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_satisfaction_mean ~ support_mean, data = survey_scored)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.30332 -0.70332 -0.01458  0.65914  2.35539 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   1.57840    0.09262   17.04   <2e-16 ***\nsupport_mean  0.48123    0.02985   16.12   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.8551 on 998 degrees of freedom\nMultiple R-squared:  0.2066,\tAdjusted R-squared:  0.2058 \nF-statistic: 259.8 on 1 and 998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model_simple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1000\n```\n\n\n:::\n:::\n\n\n散布図に回帰直線を重ねます。平均得点は0.2点刻みなので点が重なります。半透明にして、重なる場所を濃く表示します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::ggplot(survey_scored,\n                ggplot2::aes(x = support_mean, y = life_satisfaction_mean)) +\n  ggplot2::geom_point(alpha = 0.2) +\n  ggplot2::geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE) +\n  ggplot2::labs(x = \"サポート（点）\", y = \"生活満足度（点）\")\n```\n\n::: {.cell-output-display}\n![サポートと生活満足度。線は単回帰モデルによる予測値です。](simple-regression_files/figure-html/fig-regression-scatter-1.png){#fig-regression-scatter fig-alt='横軸がサポート、縦軸が生活満足度の散布図。両方とも1〜5点で、右上がりの回帰直線の周囲に点が広がっています。' width=576}\n:::\n:::\n\n\n残差とは、観測値から予測値を引いた値です。生活満足度の予測値が3点、観測値が4点なら、残差は1点です。モデルから予測値と残差を取り出し、点検用の図を作ります。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsimple_diagnostics <- data.frame(\n  fitted = fitted(model_simple),\n  residual = residuals(model_simple)\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::ggplot(simple_diagnostics, ggplot2::aes(x = fitted, y = residual)) +\n  ggplot2::geom_point(alpha = 0.2) +\n  ggplot2::geom_hline(yintercept = 0, linetype = \"dashed\") +\n  ggplot2::labs(x = \"生活満足度の予測値（点）\", y = \"残差（点）\")\n```\n\n::: {.cell-output-display}\n![単回帰モデルの予測値と残差。水平線は残差0を表します。](simple-regression_files/figure-html/fig-regression-residuals-1.png){#fig-regression-residuals fig-alt='横軸が生活満足度の予測値、縦軸が残差の散布図。残差0の上下に点があり、得点の上下限に対応して点群の外縁が斜めになっています。' width=576}\n:::\n:::\n\n\n:::\n\n## 検証チェックリスト\n\n::: {.callout-important title=\"検証チェックリスト\"}\n- [ ] 被説明変数は `life_satisfaction_mean`、説明変数は `support_mean` だけか。\n- [ ] 切片を含み、得点を標準化したり、対象を一部に絞ったりしていないか。\n- [ ] `nobs()` の分析人数は1,000人か。\n- [ ] 切片は約1.578、サポートの係数は約0.481、R² は約0.207か。\n- [ ] 散布図の軸と回帰直線は、指定した変数とモデルに対応しているか。\n- [ ] 残差の図は同じモデルから作られているか。点の中心に曲がりや、ばらつきの偏りが見えないか。\n:::\n\n数値は表示桁によって丸め方が変わります。大きく違う場合は、逆転処理と平均得点、対象者の絞り込み、回帰式を順に確かめます。\n\n`geom_smooth()` は、`method = \"lm\"` を省くと別の平滑化方法を使うことがあります。線が直線に見えるかだけでなく、コードの指定も確認してください。`se = FALSE` は回帰直線の信頼帯を隠す指定です。[ggplot2 の公式説明](https://ggplot2.tidyverse.org/reference/geom_smooth.html)\n\n残差の図では、予測値の小さい側から大きい側へ、点の中心が曲がっていないか、縦方向の広がりが変わっていないかを見ます。今回の得点には1〜5の上下限があり、残差が取りうる範囲も予測値によって変わります。点群の外縁が斜めになることには、この制約も関係します。この図だけでモデルの仮定をすべて満たすとは判断できません。詳しい点検やモデルの変更は、後の教材で扱います。\n\n## 結果の解釈\n\n### 係数と回帰直線\n\n`Coefficients` の `Estimate` 列に注目します。今回の回帰直線は、丸めると次の式です。\n\n$$\n\\widehat{\\text{生活満足度}} = 1.578 + 0.481 \\times \\text{サポート}\n$$\n\nサポートの得点が1点高い人は、生活満足度の予測値が約0.481点高いという関係です。例えば、サポートが2点の人の予測値は約2.541点、3点の人は約3.022点です。実際の生活満足度が全員この値になるわけではありません。\n\n`(Intercept)` は、サポートが0点のときの予測値です。ただし、この尺度は1〜5点なので0点の人はいません。切片は直線の位置を決める値として読み、0点の人についての実測結果とは解釈しません。\n\nこの分析は人どうしの得点の関連を表します。ある人のサポートを1点上げる介入をすれば、生活満足度が必ず0.481点上がる、という因果効果を推定したことにはなりません。\n\n### p 値と決定係数\n\n`Pr(>|t|)` は、各係数が0という帰無仮説についての p 値です。サポートの行は `p < .001` です。モデルの仮定の下で、係数0という仮説と今回の結果は整合しにくいと読みます。p 値は、帰無仮説が正しい確率や、関連の大きさを表す値ではありません。\n\n`Multiple R-squared` が決定係数 R² で、今回は約0.207です。このモデルでは、今回の生活満足度のばらつきの約20.7%を説明しています。個々の人の得点を20.7%の確率で当てる、という意味ではありません。分析人数は `nobs(model_simple)` の1,000人です。\n\n出力の列名と R² の定義は、[R の `summary.lm()` の説明](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/summary.lm.html)でも確認できます。\n\n::: {.callout-note collapse=\"true\" title=\"出力のほかの項目\"}\n`Std. Error` は係数の標準誤差、`t value` は係数をその標準誤差で割った値です。`Adjusted R-squared` は説明変数の数を考慮した調整済み決定係数です。ここでは係数、p 値、R²、分析人数を読めれば十分です。t 値と F 値の対応は、後の「t 検定・分散分析との関係」で確認します。\n:::\n\n## 年齢を加えた重回帰 {#multiple-regression}\n\n### 知りたいことと仕様の変更\n\nここまでの単回帰では、年齢の違いを考慮していませんでした。年齢が同じ人どうしを比べても、サポートの得点が高いほど生活満足度が高いのかを調べたいとします。そのために、説明変数に年齢も加えた重回帰分析を行います。\n\n| 項目 | 重回帰での仕様 |\n|---|---|\n| 対象と被説明変数 | 単回帰と同じ全員1,000人、`life_satisfaction_mean` |\n| 説明変数 | `support_mean` と `age`（年齢、20〜79歳の整数） |\n| モデル | 切片を含む重回帰。交互作用や二乗項は加えない |\n| 欲しい出力 | `summary()` の結果と分析人数。単回帰とのサポートの係数、R² の比較 |\n\n**最初のプロンプトを自分で修正し、AI にこの分析を依頼してください。** 年齢を加えることに加え、元の説明変数も残すこと、同じ対象で比べることが伝わるか確かめます。\n\n::: {.callout-caution collapse=\"true\" title=\"重回帰の参照コードと出力（実行してから開く）\"}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_multiple <- lm(\n  life_satisfaction_mean ~ support_mean + age,\n  data = survey_scored\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(model_multiple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_satisfaction_mean ~ support_mean + age, data = survey_scored)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.09636 -0.61753 -0.00707  0.60102  2.22628 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   1.03816    0.10002   10.38   <2e-16 ***\nsupport_mean  0.37609    0.02972   12.65   <2e-16 ***\nage           0.01722    0.00155   11.11   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.807 on 997 degrees of freedom\nMultiple R-squared:  0.294,\tAdjusted R-squared:  0.2926 \nF-statistic: 207.6 on 2 and 997 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model_multiple)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1000\n```\n\n\n:::\n:::\n\n\nサポートの係数と R² を、同じ人数で推定した単回帰と並べます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_comparison <- data.frame(\n  model = c(\"単回帰\", \"年齢を加えた重回帰\"),\n  support_coefficient = c(coef(model_simple)[\"support_mean\"],\n                          coef(model_multiple)[\"support_mean\"]),\n  r_squared = c(summary(model_simple)$r.squared,\n                summary(model_multiple)$r.squared),\n  n = c(nobs(model_simple), nobs(model_multiple))\n)\nmodel_comparison\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n               model support_coefficient r_squared    n\n1             単回帰           0.4812291 0.2065777 1000\n2 年齢を加えた重回帰           0.3760892 0.2940169 1000\n```\n\n\n:::\n:::\n\n\n:::\n\n### 確認と解釈\n\n::: {.callout-important title=\"重回帰の確認\"}\n- [ ] 回帰式の右側に `support_mean + age` があるか。\n- [ ] 単回帰と同じ1,000人を使っているか。\n- [ ] サポートの係数は約0.376、年齢の係数は約0.017、R² は約0.294か。\n:::\n\n| モデル | サポートの係数 | R² | 人数 |\n|---|---:|---:|---:|\n| 単回帰 | 0.481 | 0.207 | 1,000 |\n| 年齢を加えた重回帰 | 0.376 | 0.294 | 1,000 |\n\n重回帰のサポートの係数は約0.376です。これは、**年齢が同じという条件で**、サポートが1点高い人の生活満足度が平均で約0.376点高いという意味です。年齢の係数は、サポートの得点が同じという条件で、1歳年上の人の生活満足度が平均で約0.017点高いと読みます。\n\n今回のデータでは年齢がサポートとも生活満足度とも関連するため、年齢を考慮したモデルではサポートの係数が小さくなりました。重回帰でも正の関連が残っています。ただし、年齢を加えただけで因果効果が分かるわけではありません。\n\nR² は大きくなりました。同じ対象と被説明変数を使う通常の回帰では、説明変数を追加すると R² は下がりません。上がったことだけで、その変数を加えるべきだとは判断せず、分析の目的に照らして考えます。\n\n## t 検定・分散分析との関係 {#group-comparisons}\n\nMoodle で指定された場合に取り組んでください。この節では用意したコードを実行し、群平均と回帰係数、検定結果の対応を確かめます。\n\n### 2群の平均差とダミー変数\n\n就業している人を1、非就業の人を0とする `employed` を作ります。このように0と1で区分を表す変数をダミー変数といいます。正規雇用、非正規雇用、自営業等をまとめて就業者とします。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_groups <- survey_scored |>\n  dplyr::mutate(\n    employed = dplyr::if_else(employment_status == \"not_employed\", 0L, 1L)\n  )\n```\n:::\n\n\nまず2群の人数と生活満足度の平均を確認します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_groups |>\n  dplyr::group_by(employed) |>\n  dplyr::summarise(n = dplyr::n(), mean_satisfaction = mean(life_satisfaction_mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  employed     n mean_satisfaction\n     <int> <int>             <dbl>\n1        0   326              3.25\n2        1   674              2.89\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_dummy <- lm(life_satisfaction_mean ~ employed, data = survey_groups)\nsummary(model_dummy)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_satisfaction_mean ~ employed, data = survey_groups)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.25215 -0.68754 -0.05215  0.71246  2.11246 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.25215    0.05232  62.162  < 2e-16 ***\nemployed    -0.36461    0.06373  -5.722 1.39e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9446 on 998 degrees of freedom\nMultiple R-squared:  0.03176,\tAdjusted R-squared:  0.03079 \nF-statistic: 32.74 on 1 and 998 DF,  p-value: 1.395e-08\n```\n\n\n:::\n:::\n\n\n切片の約3.252は、`employed = 0`、つまり非就業者の平均です。`employed` の係数は約−0.365で、就業者の平均から非就業者の平均を引いた値です。切片に係数を足すと、就業者の平均の約2.888になります。\n\n同じ人のデータで、等分散を仮定する2群の t 検定を行います。回帰係数と差の向きをそろえるため、`x` に就業者、`y` に非就業者の得点を渡します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsatisfaction_employed <- survey_groups |>\n  dplyr::filter(employed == 1) |>\n  dplyr::pull(life_satisfaction_mean)\nsatisfaction_not_employed <- survey_groups |>\n  dplyr::filter(employed == 0) |>\n  dplyr::pull(life_satisfaction_mean)\n\ntest_employment <- t.test(\n  x = satisfaction_employed, y = satisfaction_not_employed,\n  var.equal = TRUE\n)\ntest_employment\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  satisfaction_employed and satisfaction_not_employed\nt = -5.7215, df = 998, p-value = 1.395e-08\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n -0.4896620 -0.2395583\nsample estimates:\nmean of x mean of y \n 2.887537  3.252147 \n```\n\n\n:::\n:::\n\n\n回帰の `employed` の行と t 検定を比べると、t 値はどちらも約−5.722、自由度は998、p 値は約 `1.395e-08`（$1.395 \\times 10^{-8}$）です。これは同じ対象について、等分散を置いた平均差の検定を比較した結果です。群を引く順序を逆にすると t 値の符号も逆になりますが、両側検定の p 値は変わりません。\n\n::: {.callout-note title=\"等分散 t 検定との対応\"}\n`t.test()` は既定では Welch の t 検定です。今回は通常の回帰の標準誤差と対応させるため、`var.equal = TRUE` を指定しています。常に等分散を仮定してよい、という意味ではありません。[R の `t.test()` の説明](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/t.test.html)\n:::\n\n### 4群の平均差と分散分析\n\n次は就業区分を4つのまま使います。`factor()` でカテゴリとして扱い、非就業の `not_employed` を基準にします。1、2、3、4という数値のまま回帰すると、隣り合う区分に同じ大きさの差を仮定してしまいます。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_groups <- survey_groups |>\n  dplyr::mutate(\n    employment = factor(\n      employment_status,\n      levels = c(\"not_employed\", \"regular\", \"nonregular\", \"self_employed\")\n    )\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsurvey_groups |>\n  dplyr::group_by(employment) |>\n  dplyr::summarise(\n    n = dplyr::n(),\n    mean_satisfaction = mean(life_satisfaction_mean),\n    mean_age = mean(age)\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4 × 4\n  employment        n mean_satisfaction mean_age\n  <fct>         <int>             <dbl>    <dbl>\n1 not_employed    326              3.25     60.9\n2 regular         361              2.83     40.9\n3 nonregular      175              2.87     44.5\n4 self_employed   138              3.05     51.2\n```\n\n\n:::\n:::\n\n\n4水準の因子を説明変数にすると、R は基準以外の3群を表すダミー変数を使って推定します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_groups <- lm(life_satisfaction_mean ~ employment, data = survey_groups)\nsummary(model_groups)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_satisfaction_mean ~ employment, data = survey_groups)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.25215 -0.65215 -0.03324  0.72800  2.16676 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              3.25215    0.05223  62.265  < 2e-16 ***\nemploymentregular       -0.41891    0.07205  -5.814 8.22e-09 ***\nemploymentnonregular    -0.38015    0.08837  -4.302 1.86e-05 ***\nemploymentself_employed -0.20287    0.09577  -2.118   0.0344 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.9431 on 996 degrees of freedom\nMultiple R-squared:  0.03689,\tAdjusted R-squared:  0.03399 \nF-statistic: 12.72 on 3 and 996 DF,  p-value: 3.688e-08\n```\n\n\n:::\n:::\n\n\n切片は非就業者の平均です。例えば `employmentregular` の約−0.419は、正規雇用者の平均から非就業者の平均を引いた差です。残りの2つの係数も、基準群との差として読みます。\n\n同じデータで、一元配置分散分析を実行します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova_groups <- aov(life_satisfaction_mean ~ employment, data = survey_groups)\nsummary(anova_groups)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             Df Sum Sq Mean Sq F value   Pr(>F)    \nemployment    3   33.9  11.309   12.72 3.69e-08 ***\nResiduals   996  885.8   0.889                     \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n\n\n:::\n:::\n\n\n回帰の出力末尾の `F-statistic` と、分散分析の `employment` 行の `F value` を比べてください。F 値は約12.72、自由度は3と996、p 値は約 `3.688e-08` で一致します。どちらも、4群の平均がすべて等しいという帰無仮説を検定しています。回帰の各係数についての t 検定とは、検定している仮説が異なります。\n\nここまでの群比較には、年齢を説明変数として入れていません。上の集計では群ごとに平均年齢も違います。生活満足度の平均差を、働くことの因果効果と解釈しないようにしてください。\n\n## 練習問題 {#exercises}\n\n### 問1：年齢だけを使う単回帰\n\n全員1,000人を使い、生活満足度を年齢だけに回帰してください。サポートは説明変数に入れません。対象、変数、モデル、欲しい出力を表にまとめてから、AI にコードを依頼してください。\n\n係数、p 値、R²、分析人数を表示し、年齢を横軸、生活満足度を縦軸にした散布図に回帰直線を重ねてください。年齢の係数を、単位を付けて説明してください。\n\n### 問2：動くコードの誤り探し\n\n「サポートを説明変数にしたモデルに年齢を加え、同じ年齢の人どうしでサポートと生活満足度の関係を調べたい」と指示したところ、次のコードが返ってきたとします。\n\n```{.r}\nmodel_check <- lm(life_satisfaction_mean ~ age, data = survey_scored)\nsummary(model_check)\nnobs(model_check)\n```\n\nエラーなく実行でき、人数も1,000人です。どこが仕様と違うかを指摘し、回帰式を修正してください。\n\n### 問3：結果の解釈\n\n本文の単回帰と重回帰の比較表を使い、サポートの係数0.481と0.376の違いを説明してください。さらに、「重回帰でも有意なので、サポートを増やせば生活満足度が上がると証明できた」という解釈について、どこまで言えるかを説明してください。\n\n::: {.callout-note collapse=\"true\" title=\"解答と確認のポイント（自分で解いてから開く）\"}\n\n#### 問1\n\n対象は全員、被説明変数は `life_satisfaction_mean`、説明変数は `age` です。切片を含め、変数を標準化しないモデルを指定します。\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_age <- lm(life_satisfaction_mean ~ age, data = survey_scored)\nsummary(model_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = life_satisfaction_mean ~ age, data = survey_scored)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.29998 -0.61869 -0.00668  0.61650  2.12237 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) 1.845218   0.082967   22.24   <2e-16 ***\nage         0.023464   0.001582   14.83   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.869 on 998 degrees of freedom\nMultiple R-squared:  0.1806,\tAdjusted R-squared:  0.1798 \nF-statistic:   220 on 1 and 998 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n\n```{.r .cell-code}\nnobs(model_age)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1000\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot2::ggplot(survey_scored,\n                ggplot2::aes(x = age, y = life_satisfaction_mean)) +\n  ggplot2::geom_point(alpha = 0.2) +\n  ggplot2::geom_smooth(method = \"lm\", formula = y ~ x, se = FALSE) +\n  ggplot2::labs(x = \"年齢（歳）\", y = \"生活満足度（点）\")\n```\n\n::: {.cell-output-display}\n![年齢だけで生活満足度を説明する単回帰モデル。](simple-regression_files/figure-html/fig-regression-exercise-age-1.png){#fig-regression-exercise-age fig-alt='横軸が20〜79歳の年齢、縦軸が1〜5点の生活満足度の散布図。回帰直線は右上がりです。' width=576}\n:::\n:::\n\n\n年齢の係数は約0.0235、`p < .001`、R² は約0.181、人数は1,000人です。1歳年上の人の生活満足度が平均で約0.0235点高いという関連です。このモデルではサポートの得点は考慮していません。同じ人が1歳年を取ったときの変化を追った結果でもありません。\n\n#### 問2\n\n`support_mean` が説明変数から抜けています。年齢に置き換えるのではなく、元の説明変数を残して加える必要があります。回帰式は `life_satisfaction_mean ~ support_mean + age` です。人数が合うだけでは、依頼した分析になっているとは確認できません。\n\n#### 問3\n\n0.481は年齢を考慮しないモデルでの関連、0.376は年齢が同じという条件での関連です。いずれもサポート1点の違いに対応する生活満足度の平均的な差を表します。年齢を考慮すると係数は小さくなりましたが、正の関連は残っています。\n\n年齢以外の要因や、どちらが先に変わったかは、この分析だけでは確かめられません。有意な関連があることと、介入の因果効果を証明できたことは区別します。\n\n:::\n\n## 発展（任意）\n\n共通データの変数説明を読み、関心のある数値変数の組み合わせを自分で選んで分析してください。分析対象、変数の役割、モデル、欲しい出力を先に決めます。ID のような識別番号を量的な説明変数として扱わず、どんな問いに答えるモデルなのかを説明できる組み合わせにしてください。\n\n結果の数値だけでなく、指示に合ったコードかをどう確かめ、どこを修正したかも手元に残しておくと、分析を振り返れます。\n",
    "supporting": [
      "simple-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}